# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - dev
  # 修改哪些文件会触发更新
  pull_request:
    - '.github/workflows/**'
    - 'src/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: set ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.MAC_LOCAL}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "39.100.253.134" >> ~/.ssh/known_hosts
      - name: deploy
        run: |
          ssh carr@39.100.253.143
          cd /home/carr/ww
          git remote add origin 
          git checkout develop
          git pull origin develop
          git remote remove origin
      - name: delete ssh key
        run: rm -rf ~/.ssh/id_rsa


